module TivoHME
  module Constants

    #--- Constants --------------------------------------------------------
    #
    # Mostly as defined in the HME Protocol Specification.

    HME_MAJOR_VERSION = 0
    HME_MINOR_VERSION = 49
    HME_VERSION = '%d.%d' % [HME_MAJOR_VERSION, HME_MINOR_VERSION]

    HME_MIME = 'application/x-hme'

    SAFE_ACTION_H = 32
    SAFE_ACTION_V = 24
    SAFE_TITLE_H = 64
    SAFE_TITLE_V = 48

    # Default object IDs

    ID_NULL = 0
    ID_ROOT_STREAM = 1
    ID_ROOT_VIEW = 	2
    ID_DEFAULT_TTF = 10
    ID_SYSTEM_TTF = 11

    ID_BONK_SOUND = 20
    ID_UPDOWN_SOUND = 21
    ID_THUMBSUP_SOUND = 22
    ID_THUMBSDOWN_SOUND = 23
    ID_SELECT_SOUND = 24
    ID_TIVO_SOUND = 25
    ID_LEFT_SOUND = 26
    ID_RIGHT_SOUND = 27
    ID_PAGEUP_SOUND = 28
    ID_PAGEDOWN_SOUND = 29
    ID_ALERT_SOUND = 30
    ID_DESELECT_SOUND = 31
    ID_ERROR_SOUND = 32
    ID_SLOWDOWN1_SOUND = 33
    ID_SPEEDUP1_SOUND = 34
    ID_SPEEDUP2_SOUND = 35
    ID_SPEEDUP3_SOUND = 36
    ID_SPEEDUP4_SOUND = 37  # Series 4+ only

    ID_CLIENT = 2048

    # Key actions

    KEY_PRESS = 1
    KEY_REPEAT = 2
    KEY_RELEASE = 3

    # Key codes

    KEY_UNKNOWN = 0
    KEY_TIVO = 1  # not sent
    KEY_UP = 2
    KEY_DOWN = 3
    KEY_LEFT = 4
    KEY_RIGHT = 5
    KEY_SELECT = 6
    KEY_PLAY = 7
    KEY_PAUSE = 8
    KEY_SLOW = 9
    KEY_REVERSE = 10
    KEY_FORWARD = 11
    KEY_REPLAY = 12
    KEY_ADVANCE = 13
    KEY_THUMBSUP = 14
    KEY_THUMBSDOWN = 15
    KEY_VOLUMEUP = 16
    KEY_VOLUMEDOWN = 17
    KEY_CHANNELUP = 18
    KEY_CHANNELDOWN = 19
    KEY_MUTE = 20
    KEY_RECORD = 21
    KEY_OPT_WINDOW = 22
    KEY_OPT_PIP = KEY_OPT_WINDOW
    KEY_OPT_ASPECT = KEY_OPT_WINDOW
    KEY_OPT_ZOOM = KEY_OPT_WINDOW
    KEY_LIVE_TV = 23  # not sent
    KEY_OPT_EXIT = 24  # not sent
    KEY_INFO = 25
    KEY_DISPLAY = KEY_INFO
    KEY_OPT_LIST = 26  # not sent
    KEY_OPT_GUIDE = 27  # not sent
    KEY_CLEAR = 28
    KEY_ENTER = 29
    KEY_NUM0 = 40
    KEY_NUM1 = 41
    KEY_NUM2 = 42
    KEY_NUM3 = 43
    KEY_NUM4 = 44
    KEY_NUM5 = 45
    KEY_NUM6 = 46
    KEY_NUM7 = 47
    KEY_NUM8 = 48
    KEY_NUM9 = 49
    KEY_OPT_STOP = 51
    KEY_OPT_MENU = 52
    KEY_OPT_TOP_MENU = 53
    KEY_OPT_ANGLE = 54
    KEY_OPT_DVD = 55  # not sent
    KEY_OPT_A = 56
    KEY_OPT_B = 57
    KEY_OPT_C = 58
    KEY_OPT_D = 59
    KEY_OPT_TV_POWER = 60
    KEY_OPT_TV_INPUT = 61
    KEY_OPT_VOD = 62
    KEY_OPT_POWER = 63

    KEY_BACKSPACE = 65

    # Transitions

    TRANSITION_FORWARD = 1
    TRANSITION_BACK = 2
    TRANSITION_TELEPORT = 3

    # Application errors

    APP_ERROR_UNKNOWN = 0
    APP_ERROR_BAD_ARGUMENT = 1
    APP_ERROR_BAD_COMMAND = 2
    APP_ERROR_RSRC_NOT_FOUND = 3
    APP_ERROR_VIEW_NOT_FOUND = 4
    APP_ERROR_OUT_OF_MEMORY = 5
    APP_ERROR_INVALID_TRANSITION = 6
    APP_ERROR_INVALID_RESOLUTION = 7
    APP_ERROR_OTHER = 100

    # Resource flags

    RSRC_HALIGN_LEFT = 1
    RSRC_HALIGN_CENTER = 2
    RSRC_HALIGN_RIGHT = 4
    RSRC_VALIGN_TOP = 0x10
    RSRC_VALIGN_CENTER = 0x20
    RSRC_VALIGN_BOTTOM = 0x40
    RSRC_TEXT_WRAP = 0x0100
    RSRC_IMAGE_HFIT = 0x1000
    RSRC_IMAGE_VFIT = 0x2000
    RSRC_IMAGE_BESTFIT = 0x4000

    # Resource states

    RSRC_STATUS_UNKNOWN = 0
    RSRC_STATUS_CONNECTING = 1
    RSRC_STATUS_CONNECTED = 2
    RSRC_STATUS_LOADING = 3
    RSRC_STATUS_READY = 4
    RSRC_STATUS_PLAYING = 5
    RSRC_STATUS_PAUSED = 6
    RSRC_STATUS_SEEKING = 7
    RSRC_STATUS_CLOSED = 8
    RSRC_STATUS_COMPLETE = 9
    RSRC_STATUS_ERROR = 10
    RSRC_STATUS_END = 11
    RSRC_STATUS_EOB = 12

    # Resource errors

    RSRC_ERROR_UNKNOWN = 0
    RSRC_ERROR_BAD_DATA = 1
    RSRC_ERROR_BAD_MAGIC = 2
    RSRC_ERROR_BAD_VERSION = 3
    RSRC_ERROR_CONNECTION_LOST = 4
    RSRC_ERROR_CONNECTION_TIMEOUT = 5
    RSRC_ERROR_CONNECT_FAILED = 6
    RSRC_ERROR_HOST_NOT_FOUND = 7
    RSRC_ERROR_INCOMPATIBLE = 8
    RSRC_ERROR_NOT_SUPPORTED = 9
    RSRC_ERROR_BAD_ARGUMENT = 20
    RSRC_ERROR_BAD_STATE = 	21

    # Font styles

    FONT_PLAIN = 0
    FONT_BOLD = 1
    FONT_ITALIC = 2
    FONT_BOLDITALIC = 3

    # Bitwise flags for CMD_RSRC_ADD_FONT: data to return in EVT_FONT_INFO.
    # (This is not documented in the HME spec.) Without setting one or both
    # of these flags, no EVT_FONT_INFO is returned.

    FONT_METRICS_BASIC = 1
    FONT_METRICS_GLYPH = 2

    # Commands

    CMD_VIEW_ADD = 1
    CMD_VIEW_SET_BOUNDS = 2
    CMD_VIEW_SET_SCALE = 3
    CMD_VIEW_SET_TRANSLATION = 4
    CMD_VIEW_SET_TRANSPARENCY = 5
    CMD_VIEW_SET_VISIBLE = 6
    CMD_VIEW_SET_PAINTING = 7
    CMD_VIEW_SET_RESOURCE = 8
    CMD_VIEW_REMOVE = 9

    CMD_RSRC_ADD_COLOR = 20
    CMD_RSRC_ADD_TTF = 21
    CMD_RSRC_ADD_FONT = 22
    CMD_RSRC_ADD_TEXT = 23
    CMD_RSRC_ADD_IMAGE = 24
    CMD_RSRC_ADD_SOUND = 25
    CMD_RSRC_ADD_STREAM = 26
    CMD_RSRC_ADD_ANIM = 27

    CMD_RSRC_SET_ACTIVE = 40
    CMD_RSRC_SET_POSITION = 41
    CMD_RSRC_SET_SPEED = 42

    CMD_RSRC_SEND_EVENT = 44
    CMD_RSRC_CLOSE = 45
    CMD_RSRC_REMOVE = 46

    CMD_RECEIVER_ACKNOWLEDGE_IDLE = 60
    CMD_RECEIVER_TRANSITION = 61
    CMD_RECEIVER_SET_RESOLUTION = 62

    # Events

    EVT_DEVICE_INFO = 1
    EVT_APP_INFO = 2
    EVT_RSRC_INFO = 3
    EVT_KEY = 4
    EVT_IDLE = 5
    EVT_FONT_INFO = 6
    EVT_INIT_INFO = 7
    EVT_RESOLUTION_INFO = 8

  end
end